name = "SphericalConvolutions"
uuid = "7186af5b-8736-480f-81ff-8eb527665490"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "0.1.0"

[deps]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
